spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/udesign?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.active=local
